dora-api-mock:
  stubs:
    - name: openapi
      path: \/dora\/api\/openapi.y(a)?ml
      stubFile: openapi.yaml
      mediaType: application/yaml
    - name: df_average_weekly
      path: /dora/api/metric
      stubFile: stubs/metrics/df/average_weekly.json
      mediaType: application/json
      parameters:
        type: df_average
    - name: df_average_monthly
      path: /dora/api/metric
      stubFile: stubs/metrics/df/average_monthly.json
      mediaType: application/json
      parameters:
        type: df_average
        aggregation: monthly
    - name: df_average_quarterly
      path: /dora/api/metric
      stubFile: stubs/metrics/df/average_quarterly.json
      mediaType: application/json
      parameters:
        type: df_average
        aggregation: quarterly
    - name: df_average_weekly_component
      path: /dora/api/metric
      stubFile: stubs/metrics/df/average_weekly_component.json
      mediaType: application/json
      parameters:
        type: df_average
        project: .+
    - name: df_average_monthly_component
      path: /dora/api/metric
      stubFile: stubs/metrics/df/average_monthly_component.json
      mediaType: application/json
      parameters:
        type: df_average
        aggregation: monthly
        project: .+
    - name: df_average_quarterly_component
      path: /dora/api/metric
      stubFile: stubs/metrics/df/average_quarterly_component.json
      mediaType: application/json
      parameters:
        type: df_average
        aggregation: quarterly
        project: .+
    - name: df_count_weekly
      path: /dora/api/metric
      stubFile: stubs/metrics/df/count_weekly.json
      mediaType: application/json
      parameters:
        type: df_count
    - name: df_count_monthly
      path: /dora/api/metric
      stubFile: stubs/metrics/df/count_monthly.json
      mediaType: application/json
      parameters:
        type: df_count
        aggregation: monthly
    - name: df_count_quarterly
      path: /dora/api/metric
      stubFile: stubs/metrics/df/count_quarterly.json
      mediaType: application/json
      parameters:
        type: df_count
        aggregation: quarterly
    - name: df_count_weekly_component
      path: /dora/api/metric
      stubFile: stubs/metrics/df/count_weekly_component.json
      mediaType: application/json
      parameters:
        type: df_count
        project: .+
    - name: df_count_monthly_component
      path: /dora/api/metric
      stubFile: stubs/metrics/df/count_monthly_component.json
      mediaType: application/json
      parameters:
        type: df_count
        aggregation: monthly
        project: .+
    - name: df_count_quarterly_component
      path: /dora/api/metric
      stubFile: stubs/metrics/df/count_quarterly_component.json
      mediaType: application/json
      parameters:
        type: df_count
        aggregation: quarterly
        project: .+
    - name: df_benchmark
      path: /dora/api/benchmark
      stubFile: stubs/benchmark/df/df_benchmark.json
      mediaType: application/json
      parameters:
        type: df
    - name: mltc_benchmark
      path: /dora/api/benchmark
      stubFile: stubs/benchmark/mltc/mltc_benchmark.json
      mediaType: application/json
      parameters:
        type: mltc
    - name: mltc_weekly
      path: /dora/api/metric
      stubFile: stubs/metrics/mltc/mltc_weekly.json
      mediaType: application/json
      parameters:
        type: mltc
        aggregation: weekly
    - name: mltc_weekly_component
      path: /dora/api/metric
      stubFile: stubs/metrics/mltc/mltc_weekly_component.json
      mediaType: application/json
      parameters:
        type: mltc
        aggregation: weekly
        project: .+
    - name: mltc_monthly
      path: /dora/api/metric
      stubFile: stubs/metrics/mltc/mltc_monthly.json
      mediaType: application/json
      parameters:
        type: mltc
        aggregation: monthly
    - name: mltc_monthly_component
      path: /dora/api/metric
      stubFile: stubs/metrics/mltc/mltc_monthly_component.json
      mediaType: application/json
      parameters:
        type: mltc
        aggregation: monthly
        project: .+
    - name: mltc_quarterly
      path: /dora/api/metric
      stubFile: stubs/metrics/mltc/mltc_quarterly.json
      mediaType: application/json
      parameters:
        type: mltc
        aggregation: quarterly
    - name: mltc_quarterly_component
      path: /dora/api/metric
      stubFile: stubs/metrics/mltc/mltc_quarterly_component.json
      mediaType: application/json
      parameters:
        type: mltc
        aggregation: quarterly
        project: .+

wiremock:
  server:
    port: 10666
