version: "3"
services:
  # TODO: add backstage service, including the dora-plugin
  mysql:
    image: mysql:8
    volumes:
      - mysql-storage:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: lake
      MYSQL_USER: ${DEVLAKE_MYSQL_USER:-merico}
      MYSQL_PASSWORD: ${DEVLAKE_MYSQL_PASSWORD:-merico}
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin
      --skip-log-bin

  grafana:
    profiles:
      - dashboard
    image: devlake.docker.scarf.sh/apache/devlake-dashboard:v0.18.0
    ports:
      - "3002:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: http://localhost:4000/grafana
      GF_USERS_DEFAULT_THEME: dark
      MYSQL_URL: mysql:3306
      MYSQL_DATABASE: lake
      MYSQL_USER: ${DEVLAKE_MYSQL_USER:-merico}
      MYSQL_PASSWORD: ${DEVLAKE_MYSQL_PASSWORD:-merico}
    restart: unless-stopped
    depends_on:
      - mysql

  devlake:
    image: devlake.docker.scarf.sh/apache/devlake:v0.18.0
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:z
      - ./logs:/app/logs
    environment:
      DB_URL: ${DEVLAKE_MYSQL_CONNECTION_URL:-mysql://merico:merico@mysql:3306/lake?charset=utf8mb4&parseTime=True}
      ENCRYPTION_SECRET: ${DEVLAKE_ENCRYPTION_SECRET:-}
    depends_on:
      - mysql

  config-ui:
    image: devlake.docker.scarf.sh/apache/devlake-config-ui:v0.18.0
    ports:
      - "4000:4000"
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      DEVLAKE_ENDPOINT: devlake:8080
      GRAFANA_ENDPOINT: grafana:3000
      ADMIN_USER: ${DEVLAKE_ADMIN_USER:-devlake}
      ADMIN_PASS: ${DEVLAKE_ADMIN_PASSWORD:-merico}
    depends_on:
      - devlake

volumes:
  mysql-storage:
  grafana-storage:
