name: Verify Backstage Plugin

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "backstage-plugin/**"
      - ".github/workflows/pr-backstage-plugin-workflow.yaml"

jobs:
  verify:
    name: install, lint, format, type-check, build, test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    defaults:
      run:
        working-directory: backstage-plugin

    steps:
      - uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
          cache-dependency-path: backstage-plugin/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: lint
        run: yarn lint:all

      - name: format
        run: yarn prettier:check

      - name: type checking and declarations
        run: yarn tsc

      - name: build
        run: yarn build:all

      - name: test
        run: yarn workspace @devoteam-nl/open-dora-backstage-plugin test:coverage
