name: Check Plugin
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "backstage-plugin/**"
      - ".github/workflows/pr-dora-plugin-frontend-workflow.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: backstage-plugin/plugins/dora-plugin
    steps:
      - uses: actions/checkout@v3

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
          cache-dependency-path: backstage-plugin/yarn.lock

      - name: yarn install
        uses: backstage/actions/yarn-install@v0.6.4
        with:
          cache-prefix: ${{ runner.os }}-v18.x

      - name: validate config
        run: yarn backstage-cli config:check --lax

      - name: lint
        run: yarn backstage-cli package lint

      - name: type checking and declarations
        run: yarn tsc

      - name: build
        run: yarn backstage-cli package build

      # TODO: Reenable tests once written for plugin, check that they work in new version of backstage.
      # - name: test
      #   run: yarn backstage-cli package test
