name: pr-go-packages

on:
  pull-request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: devlake-go
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go get .

      - name: Vet
        run: go vet .

      - name: Format
        run: gofmt -l -s .

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
