name: Test Go API

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "devlake-go/**"
      - ".github/workflows/pr-go-api.yaml"
      - "./.github/workflows/test/test-go-api.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "devlake-go/**"
      - ".github/workflows/pr-go-api.yaml"
      - "./.github/workflows/test/test-go-api.yaml"

jobs:
  test:
    uses: ./.github/workflows/test-go-api.yaml
