name: Check DORA API Mock
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "dora-api-mock/**"
      - ".github/workflows/pr-mock-api-workflow.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Test with Maven
        run: mvn -B verify
        working-directory: ./dora-api-mock
