name: Publish OpenDORA API Helm Chart

on:
  workflow_dispatch:
  release:
    types: [published]
    push:
      tags:
        - "*.*.*"
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | helm registry login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Package helm chart
        run: helm package open-dora-helm-chart

      - name: Publish chart to GHCR
        run: |
          export CHART_VERSION=$(grep 'version:' open-dora-helm-chart/Chart.yaml | tail -n1 | awk '{ print $2 }')
          helm push open-dora-helm-chart-${CHART_VERSION}.tgz oci://ghcr.io/devoteamnl/opendora/

      - name: Helm logout
        run: helm registry logout ghcr.io