name: Publish OpenDORA API Helm Chart

on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
    push:
      tags:
        - "*.*.*"
      branches:
        - main

jobs:
  build:
    permissions:
      contents: read
      id-token: read
      packages: write
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package helm chart
        run: helm package open-dora-helm-chart

      - name: Publish chart to GHCR
        run: |
          export CHART_VERSION=$(grep 'version:' open-dora-helm-chart/Chart.yaml | tail -n1 | awk '{ print $2 }')
          helm push open-dora-helm-chart-${CHART_VERSION}.tgz oci://ghcr.io/devoteamnl/opendora/