name: 'Test mock API'
on:
  workflow_dispatch:
  workflow_call:

jobs:
  mock:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Test with Maven
        run: mvn -B verify
        working-directory: ./dora-api-mock
